framework:
    messenger:
        # Async transport configuration for queue
        transports:
            async:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              retry_strategy:
                  max_retries: 3
                  delay: 1000
                  multiplier: 2
                  max_delay: 0

        
        # Message routing
        routing:
            'App\Service\Payment\Notification\PaymentNotificationMessage': async
